force-app/main/default/objects/Email_Validator_Setting__mdt.object
<CustomObject>
    <description>Configure the API keys and other Email Validator related settings here</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Validator Setting</label>
    <pluralLabel>Email Validator Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailValidatorLog__c.object
<CustomObject>
    <label>Email Validator Log</label>
    <nameField>
        <displayFormat>EV-LOG-{000000000}</displayFormat>
        <label>Email Validator Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Validator Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailValidatorLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <inlineHelpText>Logged Message</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailValidatorLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
                <label>Callout Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailRepEmailValidatorTest.cls
/**
 * EmailRepEmailValidatorTest
 * 
 * @description Test class validating EmailRep.io validation service
 *
 * @group EmailRep
 */
@isTest
private with sharing class EmailRepEmailValidatorTest {
    @isTest
    static List<ProspectDto> getProspectDTOs(){
        List<ProspectDto> prospects = new List<ProspectDto>();
        ProspectDto prospect = new ProspectDto();
        prospect.email = 'bill@microsoft.com';
        prospect.service = 'EmailRep';
        prospect.businessUnitId = 'fakeBusinessUnit';
        prospects.add(prospect);
        System.assertEquals('EmailRep', prospect.service,'Expecting EmailRep');
        return prospects;
    }

    @isTest
    static void testEmailRepApiSuccessHighReputation(){
        //Injection of Custom Metadata Type EmailRep_User_Agent
        SettingService.settings = new Map<String, Email_Validator_Setting__mdt>{
            'EmailRep_API_Key' => new Email_Validator_Setting__mdt(developerName = 'EmailRep_API_Key', value__c = 'QWERTZUIOP'),
            'Pardot_Named_Credential' => new Email_Validator_Setting__mdt(developerName = 'Pardot_Named_Credential', value__c = 'Pardot')
        };
        Test.startTest();
        //Set mock class callout
        Test.setMock(HttpCalloutMock.class, new EmailRepApiMock('high'));
        List<ProspectDto> prospects = getProspectDTOs();
        EmailValidatorAction.getEmailReputation(prospects);
        Test.stopTest();
        System.assertEquals(false, prospects[0].isPotentialSpam, 'Expected isPotentialSpam = false');
        List<EmailValidatorLog__c> logs = [SELECT Id, Status__c FROM EmailValidatorLog__c];
        System.assertEquals('Success', logs[0].Status__c,'Expecting success and not '+logs[0].Status__c);
    }

    @isTest
    static void testEmailRepApiSuccessLowReputation(){
        //Injection of Custom Metadata Type
        SettingService.settings = new Map<String, Email_Validator_Setting__mdt>{
            'EmailRep_API_Key' => new Email_Validator_Setting__mdt(developerName = 'EmailRep_API_Key', value__c = 'QWERTZUIOP'),
            'Pardot_Named_Credential' => new Email_Validator_Setting__mdt(developerName = 'Pardot_Named_Credential', value__c = 'Pardot')
        };
        Test.startTest();
        //Set mock class callout
        Test.setMock(HttpCalloutMock.class, new EmailRepApiMock('low'));
        List<ProspectDto> prospects = getProspectDTOs();
        EmailValidatorAction.getEmailReputation(prospects);
        Test.stopTest();
        System.assertEquals(true, prospects[0].isPotentialSpam, 'Expected isPotentialSpam = true');
        List<EmailValidatorLog__c> logs = [SELECT Id, Status__c FROM EmailValidatorLog__c];
        System.assertEquals('Success', logs[0].Status__c,'Expecting success and not '+logs[0].Status__c);
    } 

    @isTest
    static void testEmailRepApiServiceSettingException(){
        //Injection of Custom Metadata Type
        SettingService.settings = new Map<String, Email_Validator_Setting__mdt>();
        Test.startTest();
        //Set mock class callout
        Test.setMock(HttpCalloutMock.class, new EmailRepApiMock(200));
        List<ProspectDto> prospects = getProspectDTOs();
        EmailValidatorAction.getEmailReputation(prospects);
        Test.stopTest();
        System.assertEquals(null, prospects[0].isPotentialSpam, 'Expected isPotentialSpam = null');
        List<EmailValidatorLog__c> logs = [SELECT Id, Status__c, Message__c FROM EmailValidatorLog__c];
        System.assertEquals('Error', logs[0].Status__c,'Expecting success and not '+logs[0].Status__c);
        System.assertEquals('MissingSettingException', logs[0].Message__c,'Expecting MissingSettingException and not '+logs[0].Message__c);
    }

    @isTest
    static void testEmailRepApiPardotSettingException(){
        //Injection of Custom Metadata Type
        SettingService.settings = new Map<String, Email_Validator_Setting__mdt>{
            'EmailRep_API_Key' => new Email_Validator_Setting__mdt(developerName = 'EmailRep_API_Key', value__c = 'QWERTZUIOP')
        };
        Test.startTest();
        //Set mock class callout
        Test.setMock(HttpCalloutMock.class, new EmailRepApiMock(200));
        List<ProspectDto> prospects = getProspectDTOs();
        EmailValidatorAction.getEmailReputation(prospects);
        Test.stopTest();
        System.assertEquals(false, prospects[0].isPotentialSpam, 'Expected isPotentialSpam = false');
        List<EmailValidatorLog__c> logs = [SELECT Id, Status__c, Message__c FROM EmailValidatorLog__c];
        System.assertEquals('Success', logs[0].Status__c,'Expecting success and not '+logs[0].Status__c);
        System.assertEquals('Error', logs[1].Status__c,'Expecting success and not '+logs[0].Status__c);
        System.assertEquals('MissingSettingException', logs[1].Message__c,'Expecting MissingSettingException and not '+logs[0].Message__c);
    }
    
    @isTest
    static void testEmailRepApiExternalServiceException(){
        //Injection of Custom Metadata Type
        SettingService.settings = new Map<String, Email_Validator_Setting__mdt>{
            'EmailRep_API_Key' => new Email_Validator_Setting__mdt(developerName = 'EmailRep_API_Key', value__c = 'QWERTZUIOP'),
            'Pardot_Named_Credential' => new Email_Validator_Setting__mdt(developerName = 'Pardot_Named_Credential', value__c = 'Pardot')
        };
        Test.startTest();
        //Set mock class callout
        Test.setMock(HttpCalloutMock.class, new EmailRepApiMock(301));
        List<ProspectDto> prospects = getProspectDTOs();
        EmailValidatorAction.getEmailReputation(prospects);
        Test.stopTest();
        System.assertEquals(null, prospects[0].isPotentialSpam, 'Expected isPotentialSpam = null');
        List<EmailValidatorLog__c> logs = [SELECT Id, Status__c, Message__c FROM EmailValidatorLog__c];
        System.assertEquals('Error', logs[0].Status__c,'Expecting success and not '+logs[0].Status__c);
        System.assertEquals('ExternalServiceException', logs[0].Message__c,'Expecting ExternalServiceException and not '+logs[0].Message__c);
    }

    @isTest
    static void testEmailRepApiJsonException(){
        //Injection of Custom Metadata Type
        SettingService.settings = new Map<String, Email_Validator_Setting__mdt>{
            'EmailRep_API_Key' => new Email_Validator_Setting__mdt(developerName = 'EmailRep_API_Key', value__c = 'QWERTZUIOP'),
            'Pardot_Named_Credential' => new Email_Validator_Setting__mdt(developerName = 'Pardot_Named_Credential', value__c = 'Pardot')
        };
        Test.startTest();
        //Set mock class callout
        Test.setMock(HttpCalloutMock.class, new EmailRepApiMock(true));
        List<ProspectDto> prospects = getProspectDTOs();
        EmailValidatorAction.getEmailReputation(prospects);
        Test.stopTest();
        System.assertEquals(null, prospects[0].isPotentialSpam, 'Expected isPotentialSpam = null');
        List<EmailValidatorLog__c> logs = [SELECT Id, Status__c, Message__c FROM EmailValidatorLog__c];
        System.assertEquals('Error', logs[0].Status__c,'Expecting success and not '+logs[0].Status__c);
        System.assertEquals('JSONException', logs[0].Message__c,'Expecting JSONException and not '+logs[0].Message__c);
    }
}