force-app/main/default/objects/Email_Validator_Setting__mdt.object
<CustomObject>
    <description>Configure the API keys and other Email Validator related settings here</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Validator Setting</label>
    <pluralLabel>Email Validator Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/SettingService.cls
/**
 * SettingService 
 * 
 * @description Utility class to interact with the CMT Settings
 * 
 * @group EmailValidator
 */
public with sharing class SettingService {
 
    @testVisible
    private static Map<String, Email_Validator_Setting__mdt> settings;
 
    public static String getSettingValue(String key){
        if(settings==null){
            settings = Email_Validator_Setting__mdt.getAll();
        }
        return settings.get(key)?.value__c;
    }

    public class MissingSettingException extends Exception {}
}